/*
-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S




-- 2022년 1월 기준
-- 북 테이블에서 북 아이디, 가격 
-- 북 테이블에서 카테고리랑 작가별 


SELECT AUTHOR_NAME, CATEGORY, PRICE, SALES, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S
*/

/*
-- 토탈 세일 테이블. 북, 북 세일즈 -> 세일즈 날짜 2022년 1월 기준. 북 id 에 따른 판매량. * 가격
WITH TOTAL AS (
    SELECT B.BOOK_ID, S.SALES_DATE, S.SALES, B.PRICE, (B.PRICE * S.SALES) AS TOTAL_SALES 
    FROM BOOK B, BOOK_SALES S
)
*/

    SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES 
    FROM BOOK B, BOOK_SALES S, AUTHOR A
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    AND B.AUTHOR_ID = A.AUTHOR_ID
    and B.BOOK_ID = S.BOOK_ID
    GROUP BY B.CATEGORY, B.AUTHOR_ID
    ORDER BY AUTHOR_ID, CATEGORY desc

