SELECT 
    EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) 
                                      FROM USER_INFO 
                                      WHERE JOINED >= DATE '2021-01-01'
                                      AND JOINED < DATE '2022-01-01')
    , 1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
WHERE U.JOINED >= DATE '2021-01-01'
  AND U.JOINED < DATE '2022-01-01'
GROUP BY 
    EXTRACT(YEAR FROM S.SALES_DATE),
    EXTRACT(MONTH FROM S.SALES_DATE)
ORDER BY YEAR, MONTH;