-- 코드를 입력하세요
-- /home/grep/src/
# SELECT CONCAT('/home/grep/src/',`B.BOARD_ID`,`/`,`F.FILE_ID`,`F.FILE_NAME`,`F.FILE_EXT`) AS FILE_PATH
SELECT CONCAT('/home/grep/src/',A.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_FILE F
ON A.BOARD_ID = F.BOARD_ID
WHERE A.VIEWS =
    (SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD A)
